#!/usr/bin/env bash

set -e -o pipefail
# set -x # debug

BASE_CONFIG="base"
CONFIG_SUFFIX=".yaml"

CONFIG_DIR="configs"
PROFILES_DIR="profiles"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASE_DIR}"
git -C "${BASE_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${BASE_DIR}"

profile_path="${PROFILES_DIR}/$1"
[[ -d $profile_path ]] && profile_path="${profile_path}/default"

while IFS= read -r config; do
    CONFIGS+=" ${config}"
done < "$profile_path"

shift

echo "BASE_DIR: ${BASE_DIR}"
echo "CONFIG_DIR: ${CONFIG_DIR}"
echo "CONFIG_SUFFIX: ${CONFIG_SUFFIX}"

for config in ${CONFIGS} ${@}; do
    configFile="$(mktemp)" # create temporary file

    echo -e "\nConfigure $config — ${configFile}"

    suffix="-sudo"

    # 1) prepend base.yaml if it exists (errors suppressed)
    cat "${BASE_DIR}/${CONFIG_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}" 2>/dev/null >"$configFile" || true

    # 2) append the profile-listed config
    cat "${BASE_DIR}/${CONFIG_DIR}/${config%"$suffix"}${CONFIG_SUFFIX}" >>"$configFile"

    cmd=("${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -v -d "${BASE_DIR}" -c "$configFile")

    if [[ $config == *"sudo"* ]]; then
        cmd=(sudo "${cmd[@]}")
    fi

    echo "CMD: "${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -v -d "${BASE_DIR}" -c "$configFile""

    "${cmd[@]}"
    rm -f "$configFile"
done

cd "${BASE_DIR}"