#!/usr/bin/env bash

set -ex

BASE_CONFIG="base"
CONFIG_SUFFIX=".yaml"

CONFIG_DIR="configs"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASE_DIR}"
git submodule update --init --recursive --remote

for config in ${@}; do
    configFile="$(mktemp)" # create temporary file

    suffix="-sudo"

    # 1) write base.yaml (if you keep one)
    cat "${BASE_DIR}/${CONFIG_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}" 2>/dev/null > "$configFile" || true

    # 2) append the feature-specific config
    cat "${BASE_DIR}/${CONFIG_DIR}/${config%"$suffix"}${CONFIG_SUFFIX}" >> "$configFile"

    cmd=("${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" -c "$configFile")

    if [[ $config == *"sudo"* ]]; then
        cmd=(sudo "${cmd[@]}")
    fi

    "${cmd[@]}"
    rm -f "$configFile"
done

cd "${BASE_DIR}"