cask_args appdir: '/Applications'

# Tap it
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/core'
tap 'homebrew/services'

# Cask it
cask 'firefox'
cask 'rectangle'
cask 'lens'

# Brewwwwww it
brew 'postgresql'
brew 'redis'

brew 'pyenv'
brew 'pyenv-virtualenv'

brew 'go'
brew 'fzf'
brew 'glow'

brew 'fd'
brew 'ripgrep'
brew 'exa'
brew 'git-delta'

brew 'tmux'
brew 'wget'

brew 'gawk'
brew 'htop'
brew 'gpg'
brew 'exiftool'

brew 'exercism'

brew 'tree-sitter', args: ['HEAD']
brew 'luajit', args: ['HEAD']
brew 'vim'
brew 'neovim', args: ['HEAD']

brew 'nvm'
brew 'awscli'
brew 'kubectl'
brew 'helm'
brew 'helmfile'
brew 'https://github.com/databus23/helm-diff'
brew 'ipfs'
brew 'ffmpeg'
brew 'tealdeer'
brew 'k3sup'
brew 'httpie'
brew 'jq'
brew 'lxc'
# brew 'gromgit/fuse/XYZ-mac'
# brew 'gromgit/fuse/sshfs-mac'
# brew 'gromgit/fuse/sshfs-mac'
brew 'syncthing'
brew 'byobu'
brew 'minicom'